# Generated by Django 5.1.4 on 2026-04-10 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('team_name', models.CharField(blank=True, max_length=120)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('default_role', models.CharField(choices=[('analyst', 'Analyst'), ('manager', 'Manager'), ('ops_operator', 'Operations Operator'), ('platform_admin', 'Platform Admin')], default='analyst', max_length=32)),
                ('clearance_level', models.CharField(choices=[('internal', 'Internal'), ('restricted', 'Restricted'), ('confidential', 'Confidential')], default='internal', max_length=32)),
                ('is_on_call', models.BooleanField(default=False)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'permissions': [('manage_rbac', 'Can manage platform RBAC bootstrap and role bindings')],
            },
        ),
    ]
