# Generated by Django 5.1.4 on 2026-04-10 22:21

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedArticleCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('normalized', 'Normalized'), ('article_created', 'Article Created'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RawItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=1000)),
                ('title_raw', models.TextField(blank=True)),
                ('content_raw', models.TextField(blank=True)),
                ('html_raw', models.TextField(blank=True)),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('fetched', 'Fetched'), ('parsed', 'Parsed'), ('normalized', 'Normalized'), ('article_created', 'Article Created'), ('failed', 'Failed')], default='fetched', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('raw_storage_key', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(db_index=True, max_length=1000)),
                ('canonical_url', models.URLField(blank=True, max_length=1000)),
                ('title', models.CharField(max_length=500)),
                ('normalized_title', models.CharField(db_index=True, max_length=500)),
                ('content', models.TextField()),
                ('normalized_content', models.TextField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('matched_rule_labels', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('importance_score', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('quality_score', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='sources.article')),
                ('matched_topics', models.ManyToManyField(blank=True, related_name='articles', to='topics.topic')),
            ],
            options={
                'ordering': ['-published_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('normalized_name', models.CharField(db_index=True, max_length=300)),
                ('canonical_name', models.CharField(blank=True, db_index=True, help_text="Canonical form of this entity (e.g. 'United States' for 'USA').", max_length=300)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='Known alternative names / abbreviations for this entity.')),
                ('entity_type', models.CharField(choices=[('person', 'Person'), ('location', 'Location'), ('organization', 'Organization')], db_index=True, max_length=16)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'entities',
                'ordering': ['normalized_name'],
                'indexes': [models.Index(fields=['entity_type'], name='sources_ent_entity__4bac68_idx')],
                'constraints': [models.UniqueConstraint(fields=('normalized_name', 'entity_type'), name='uniq_entity_name_type')],
            },
        ),
        migrations.CreateModel(
            name='ArticleEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relevance_score', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4)),
                ('mention_count', models.PositiveIntegerField(default=1)),
                ('context_snippet', models.TextField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_entities', to='sources.article')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_entities', to='sources.entity')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='entities',
            field=models.ManyToManyField(blank=True, related_name='articles', through='sources.ArticleEntity', to='sources.entity'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('unknown', 'Unknown'), ('strike', 'Strike'), ('explosion', 'Explosion'), ('protest', 'Protest'), ('political', 'Political Event'), ('conflict', 'Armed Conflict'), ('disaster', 'Natural Disaster'), ('economic', 'Economic Event'), ('diplomacy', 'Diplomacy'), ('crime', 'Crime'), ('health', 'Health Event'), ('technology', 'Technology'), ('other', 'Other')], db_index=True, default='unknown', max_length=24)),
                ('location_name', models.CharField(blank=True, max_length=300)),
                ('location_country', models.CharField(blank=True, max_length=2)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('first_reported_at', models.DateTimeField(blank=True, null=True)),
                ('last_reported_at', models.DateTimeField(blank=True, null=True)),
                ('story_count', models.PositiveIntegerField(default=0)),
                ('source_count', models.PositiveIntegerField(default=0)),
                ('importance_score', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('confidence_score', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('geo_confidence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('conflict_flag', models.BooleanField(db_index=True, default=False)),
                ('timeline_json', models.JSONField(blank=True, default=list, help_text='Chronological list of event updates [{ts, summary, source_id}].')),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-last_reported_at', '-updated_at'],
                'indexes': [models.Index(fields=['event_type'], name='sources_eve_event_t_e10de1_idx'), models.Index(fields=['first_reported_at'], name='sources_eve_first_r_09c354_idx'), models.Index(fields=['last_reported_at'], name='sources_eve_last_re_974bcb_idx'), models.Index(fields=['confidence_score'], name='sources_eve_confide_d8621d_idx'), models.Index(fields=['conflict_flag'], name='sources_eve_conflic_ee7e6d_idx')],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='parsed_candidate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='sources.parsedarticlecandidate'),
        ),
        migrations.AddField(
            model_name='parsedarticlecandidate',
            name='raw_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_candidate', to='sources.rawitem'),
        ),
        migrations.AddField(
            model_name='article',
            name='raw_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to='sources.rawitem'),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('rss', 'RSS'), ('sitemap', 'Sitemap'), ('html', 'HTML'), ('api', 'API')], default='rss', max_length=24)),
                ('parser_type', models.CharField(choices=[('rss', 'RSS'), ('sitemap', 'Sitemap'), ('html', 'HTML'), ('gdelt', 'GDELT'), ('scrapy_ingestion', 'Scrapy Ingestion')], default='rss', max_length=32)),
                ('base_url', models.URLField(blank=True)),
                ('endpoint_url', models.URLField(blank=True)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('trust_score', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=4)),
                ('total_articles_fetched', models.PositiveIntegerField(default=0)),
                ('total_duplicates', models.PositiveIntegerField(default=0)),
                ('total_low_quality', models.PositiveIntegerField(default=0)),
                ('avg_quality_score', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('fetch_interval_minutes', models.PositiveIntegerField(default=30)),
                ('default_language', models.CharField(blank=True, max_length=16)),
                ('default_country', models.CharField(blank=True, max_length=2)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('health_status', models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('degraded', 'Degraded'), ('failing', 'Failing')], default='unknown', max_length=20)),
                ('polling_interval_minutes', models.PositiveIntegerField(default=30)),
                ('request_timeout_seconds', models.PositiveIntegerField(default=30)),
                ('is_public', models.BooleanField(default=True)),
                ('parser_config', models.JSONField(blank=True, default=dict)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='rawitem',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_items', to='sources.source'),
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='sources.source'),
        ),
        migrations.CreateModel(
            name='SourceFetchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20)),
                ('items_fetched', models.PositiveIntegerField(default=0)),
                ('items_created', models.PositiveIntegerField(default=0)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_runs', to='sources.source')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceFetchError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(blank=True)),
                ('error', models.TextField()),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_errors', to='sources.source')),
                ('fetch_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to='sources.sourcefetchrun')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='rawitem',
            name='fetch_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_items', to='sources.sourcefetchrun'),
        ),
        migrations.CreateModel(
            name='SourceHealthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('health_status', models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('degraded', 'Degraded'), ('failing', 'Failing')], default='unknown', max_length=20)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_events', to='sources.source')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story_key', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('first_published_at', models.DateTimeField(blank=True, null=True)),
                ('last_published_at', models.DateTimeField(blank=True, null=True)),
                ('article_count', models.PositiveIntegerField(default=0)),
                ('importance_score', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='sources.event')),
            ],
            options={
                'ordering': ['-last_published_at', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='sources.story'),
        ),
        migrations.AddConstraint(
            model_name='articleentity',
            constraint=models.UniqueConstraint(fields=('article', 'entity'), name='uniq_article_entity'),
        ),
        migrations.AddIndex(
            model_name='parsedarticlecandidate',
            index=models.Index(fields=['status'], name='sources_par_status_ff0518_idx'),
        ),
        migrations.AddIndex(
            model_name='parsedarticlecandidate',
            index=models.Index(fields=['published_at'], name='sources_par_publish_136982_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['source_type'], name='sources_sou_source__5290ea_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['parser_type'], name='sources_sou_parser__b42d1e_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['status'], name='sources_sou_status_88455e_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['health_status'], name='sources_sou_health__d82704_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['is_active'], name='sources_sou_is_acti_01a13f_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcefetchrun',
            index=models.Index(fields=['status'], name='sources_sou_status_2a9121_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcefetchrun',
            index=models.Index(fields=['started_at'], name='sources_sou_started_144349_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcefetcherror',
            index=models.Index(fields=['timestamp'], name='sources_sou_timesta_641a03_idx'),
        ),
        migrations.AddIndex(
            model_name='rawitem',
            index=models.Index(fields=['status'], name='sources_raw_status_d0ce4a_idx'),
        ),
        migrations.AddIndex(
            model_name='rawitem',
            index=models.Index(fields=['fetched_at'], name='sources_raw_fetched_18d87f_idx'),
        ),
        migrations.AddConstraint(
            model_name='rawitem',
            constraint=models.UniqueConstraint(fields=('source', 'url', 'content_hash'), name='uniq_raw_item_source_url_hash'),
        ),
        migrations.AddIndex(
            model_name='sourcehealthevent',
            index=models.Index(fields=['health_status'], name='sources_sou_health__32178b_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcehealthevent',
            index=models.Index(fields=['created_at'], name='sources_sou_created_c5f627_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['content_hash'], name='sources_art_content_9eef06_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_duplicate'], name='sources_art_is_dupl_a59f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published_at'], name='sources_art_publish_bc00e0_idx'),
        ),
    ]
