# Generated by Django 5.1.4 on 2026-04-12 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='parser_type',
            field=models.CharField(choices=[('rss', 'RSS'), ('sitemap', 'Sitemap'), ('html', 'HTML'), ('gdelt', 'GDELT'), ('newsapi', 'NewsAPI'), ('scrapy_ingestion', 'Scrapy Ingestion')], default='rss', max_length=32),
        ),
        migrations.CreateModel(
            name='ArticleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language_code', models.CharField(db_index=True, max_length=10)),
                ('translated_title', models.CharField(blank=True, max_length=1000)),
                ('translated_body', models.TextField(blank=True)),
                ('translation_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('translated_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='sources.article')),
            ],
            options={
                'indexes': [models.Index(fields=['language_code'], name='sources_art_languag_3c693b_idx'), models.Index(fields=['translation_status'], name='sources_art_transla_301b00_idx')],
                'constraints': [models.UniqueConstraint(fields=('article', 'language_code'), name='uniq_article_translation_lang')],
            },
        ),
    ]
