# Generated by Django 5.1.4 on 2026-04-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_add_article_ai_summary'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='articleaisummary',
            new_name='sources_art_status_e715dc_idx',
            old_name='sources_arti_status_ai_idx',
        ),
        migrations.AlterField(
            model_name='source',
            name='parser_type',
            field=models.CharField(choices=[('rss', 'RSS'), ('sitemap', 'Sitemap'), ('html', 'HTML'), ('gdelt', 'GDELT'), ('newsapi', 'NewsAPI'), ('gnews', 'GNews'), ('scrapy_ingestion', 'Scrapy Ingestion')], default='rss', max_length=32),
        ),
    ]
