# Generated by Django 5.1.4 on 2026-04-13 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0006_intel_assessment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='eventintelassessment',
            new_name='sources_eve_status_0b93ea_idx',
            old_name='sources_eve_status_intel_idx',
        ),
        migrations.RenameIndex(
            model_name='eventintelassessment',
            new_name='sources_eve_verific_686af5_idx',
            old_name='sources_eve_verif_idx',
        ),
        migrations.RenameIndex(
            model_name='eventintelassessment',
            new_name='sources_eve_credibi_7a34f4_idx',
            old_name='sources_eve_cred_idx',
        ),
    ]
