# Generated by Django 5.1.4 on 2026-04-17 20:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0010_merge_language_and_self_learning'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='merge_confidence',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Confidence score (0–1) of the canonical merge decision.', max_digits=4),
        ),
        migrations.AddField(
            model_name='entity',
            name='merge_method',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('rule', 'Rule-Based'), ('embedding', 'Embedding-Based'), ('ai', 'AI-Assisted'), ('hybrid', 'Hybrid')], default='none', help_text='Method used to establish the canonical form.', max_length=16),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['merge_method'], name='sources_ent_merge_m_344237_idx'),
        ),
    ]
