# Generated by Django 5.1.4

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0011_entity_merge_provenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityMergeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_entity_id', models.IntegerField(help_text='PK of the entity that was merged (may no longer exist).')),
                ('source_entity_name', models.CharField(max_length=300)),
                ('source_entity_type', models.CharField(max_length=16)),
                ('source_entity_canonical', models.CharField(blank=True, max_length=300)),
                ('source_article_count', models.PositiveIntegerField(default=0)),
                ('source_aliases', models.JSONField(blank=True, default=list)),
                ('target_entity_name', models.CharField(max_length=300)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('merge_method', models.CharField(choices=[('registry', 'Alias Registry'), ('normalization', 'Arabic Normalization'), ('embedding', 'Embedding Similarity'), ('hybrid', 'Hybrid'), ('manual', 'Manual (Admin)')], max_length=20)),
                ('merge_reason', models.TextField(blank=True)),
                ('article_evidence', models.JSONField(blank=True, default=list, help_text='List of article IDs used as context evidence.')),
                ('rolled_back', models.BooleanField(db_index=True, default=False)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('rollback_note', models.TextField(blank=True)),
                ('rolled_back_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_rollbacks', to=settings.AUTH_USER_MODEL)),
                ('target_entity', models.ForeignKey(blank=True, help_text='The surviving canonical entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_audit_as_target', to='sources.entity')),
            ],
            options={
                'verbose_name': 'Entity Merge Audit',
                'verbose_name_plural': 'Entity Merge Audits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_entity_id'], name='sources_ent_source__f5dd01_idx'), models.Index(fields=['merge_method'], name='sources_ent_merge_m_a887fc_idx'), models.Index(fields=['rolled_back'], name='sources_ent_rolled__d564e6_idx'), models.Index(fields=['created_at'], name='sources_ent_created_0d38f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='EntityReviewQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('similarity_score', models.DecimalField(decimal_places=4, help_text='Raw embedding / normalization similarity score (0–1).', max_digits=5)),
                ('context_score', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Context compatibility score from co-occurring entity analysis.', max_digits=5)),
                ('final_score', models.DecimalField(decimal_places=4, help_text='Final merged confidence score used for the decision.', max_digits=5)),
                ('merge_method', models.CharField(choices=[('registry', 'Alias Registry'), ('normalization', 'Arabic Normalization'), ('embedding', 'Embedding Similarity'), ('hybrid', 'Hybrid')], default='embedding', max_length=20)),
                ('explanation', models.TextField(blank=True, help_text='Human-readable explanation of why the match was proposed.')),
                ('supporting_article_ids', models.JSONField(blank=True, default=list, help_text='List of article IDs providing context evidence.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_merged', 'Auto-Merged'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('candidate_entity', models.ForeignKey(help_text='The new / unresolved entity proposed for merging.', on_delete=django.db.models.deletion.CASCADE, related_name='review_queue_as_candidate', to='sources.entity')),
                ('matched_entity', models.ForeignKey(help_text='The existing canonical entity this candidate may represent.', on_delete=django.db.models.deletion.CASCADE, related_name='review_queue_as_match', to='sources.entity')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entity Review Queue Item',
                'verbose_name_plural': 'Entity Review Queue',
                'ordering': ['-final_score', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='sources_ent_status_bee0e9_idx'), models.Index(fields=['final_score'], name='sources_ent_final_s_3870f0_idx'), models.Index(fields=['merge_method'], name='sources_ent_merge_m_021cd9_idx')],
            },
        ),
    ]
