# Generated by Django 5.1.4

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0012_entity_review_queue_merge_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityInfluenceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree_centrality', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), help_text='Number of unique entity relationships (normalised).', max_digits=7)),
                ('weighted_degree', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), help_text='Sum of relationship strength scores.', max_digits=7)),
                ('mentions_last_24h', models.PositiveIntegerField(default=0)),
                ('mentions_last_7d', models.PositiveIntegerField(default=0)),
                ('mentions_last_30d', models.PositiveIntegerField(default=0)),
                ('velocity_score', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Normalised mention velocity (0–1).', max_digits=6)),
                ('growth_flag', models.BooleanField(db_index=True, default=False, help_text='Set when mentions_last_24h is ≥ 2× the 7-day daily average.')),
                ('influence_rank', models.PositiveIntegerField(db_index=True, default=0, help_text='Rank by influence (1 = most influential).')),
                ('influence_score', models.DecimalField(db_index=True, decimal_places=5, default=Decimal('0.00000'), max_digits=7)),
                ('scored_at', models.DateTimeField(auto_now=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='influence_score', to='sources.entity')),
            ],
            options={
                'verbose_name': 'Entity Influence Score',
                'verbose_name_plural': 'Entity Influence Scores',
                'ordering': ['influence_rank'],
                'indexes': [models.Index(fields=['influence_score'], name='sources_ent_influen_738e43_idx'), models.Index(fields=['growth_flag'], name='sources_ent_growth__748906_idx'), models.Index(fields=['velocity_score'], name='sources_ent_velocit_d84338_idx')],
            },
        ),
        migrations.CreateModel(
            name='EntityRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_occurrence_count', models.PositiveIntegerField(default=0, help_text='Total number of articles where both entities appear.')),
                ('strength_score', models.DecimalField(db_index=True, decimal_places=4, default=Decimal('0.0000'), help_text='Weighted relationship strength (0–1).', max_digits=6)),
                ('confidence', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Confidence in this relationship (0–1).', max_digits=5)),
                ('recency_score', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Boost from recency of co-occurring articles.', max_digits=5)),
                ('source_diversity_score', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Fraction of distinct sources that mention this pair.', max_digits=5)),
                ('relationship_type', models.CharField(choices=[('political', 'Political'), ('military', 'Military'), ('economic', 'Economic'), ('diplomatic', 'Diplomatic'), ('conflict', 'Conflict'), ('social', 'Social'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=16)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Published date of the most recent co-occurring article.', null=True)),
                ('first_seen_at', models.DateTimeField(blank=True, help_text='Published date of the earliest co-occurring article.', null=True)),
                ('supporting_article_ids', models.JSONField(blank=True, default=list, help_text='Up to 20 most-recent article IDs evidencing this relationship.')),
                ('supporting_source_ids', models.JSONField(blank=True, default=list, help_text='Distinct source IDs that reported this relationship.')),
                ('prev_co_occurrence_count', models.PositiveIntegerField(default=0, help_text='Co-occurrence count as of the last scoring run (for growth detection).')),
                ('growth_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Relative growth in co-occurrences since last run.', max_digits=6)),
                ('entity_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_a', to='sources.entity')),
                ('entity_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_b', to='sources.entity')),
            ],
            options={
                'verbose_name': 'Entity Relationship',
                'verbose_name_plural': 'Entity Relationships',
                'ordering': ['-strength_score'],
                'indexes': [models.Index(fields=['entity_a', 'strength_score'], name='sources_ent_entity__5b72a2_idx'), models.Index(fields=['entity_b', 'strength_score'], name='sources_ent_entity__f9aa33_idx'), models.Index(fields=['relationship_type'], name='sources_ent_relatio_66aad7_idx'), models.Index(fields=['last_seen_at'], name='sources_ent_last_se_359a6d_idx'), models.Index(fields=['strength_score'], name='sources_ent_strengt_f07abc_idx'), models.Index(fields=['growth_rate'], name='sources_ent_growth__4811b8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('entity_a__lt', models.F('entity_b'))), fields=('entity_a', 'entity_b'), name='uniq_entity_relationship')],
            },
        ),
        migrations.CreateModel(
            name='EntitySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signal_type', models.CharField(choices=[('mention_spike', 'Sudden Mention Spike'), ('new_relationship', 'New Strong Relationship'), ('unusual_pair', 'Unusual Entity Connection'), ('rapid_growth', 'Rapidly Growing Entity'), ('relationship_decay', 'Relationship Decay')], db_index=True, max_length=24)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, default='medium', max_length=8)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Signal-type-specific data (e.g. spike ratio, related entity id).')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this signal is no longer relevant.', null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='sources.entity')),
                ('related_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals_as_related', to='sources.entity')),
            ],
            options={
                'verbose_name': 'Entity Signal',
                'verbose_name_plural': 'Entity Signals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['signal_type'], name='sources_ent_signal__785604_idx'), models.Index(fields=['severity'], name='sources_ent_severit_5e7875_idx'), models.Index(fields=['is_read'], name='sources_ent_is_read_47a5e7_idx'), models.Index(fields=['created_at'], name='sources_ent_created_7fbc1c_idx')],
            },
        ),
    ]
