# Generated by Django 5.1.4 on 2026-04-10 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('geography_focus', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_topics', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('watchlist_type', models.CharField(choices=[('entity', 'Entity'), ('organization', 'Organization'), ('location', 'Location'), ('theme', 'Theme'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchlists_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_watchlists', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to='topics.topic')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='watchlists_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['topic__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KeywordRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=200)),
                ('pattern', models.TextField()),
                ('normalized_pattern', models.CharField(blank=True, editable=False, max_length=512)),
                ('rule_type', models.CharField(choices=[('keyword', 'Keyword'), ('phrase', 'Phrase'), ('boolean', 'Boolean'), ('regex', 'Regex')], default='keyword', max_length=20)),
                ('match_target', models.CharField(choices=[('any', 'Any'), ('title', 'Title'), ('body', 'Body'), ('url', 'URL')], default='any', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('is_exclusion', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keyword_rules_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keyword_rules_updated', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_rules', to='topics.topic')),
                ('watchlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyword_rules', to='topics.watchlist')),
            ],
            options={
                'ordering': ['topic__name', 'label'],
            },
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['status'], name='topics_topi_status_54d68a_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['priority'], name='topics_topi_priorit_fe2f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['status'], name='topics_watc_status_a7dc6f_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['watchlist_type'], name='topics_watc_watchli_e56de9_idx'),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(fields=('topic', 'name'), name='uniq_watchlist_per_topic'),
        ),
        migrations.AddIndex(
            model_name='keywordrule',
            index=models.Index(fields=['enabled'], name='topics_keyw_enabled_85755a_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordrule',
            index=models.Index(fields=['rule_type'], name='topics_keyw_rule_ty_48c0d5_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordrule',
            index=models.Index(fields=['match_target'], name='topics_keyw_match_t_27b959_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordrule',
            index=models.Index(fields=['priority'], name='topics_keyw_priorit_d61ad0_idx'),
        ),
    ]
