# Generated by Django 5.1.4 on 2026-04-10 22:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('on_hold', 'On Hold'), ('closed', 'Closed'), ('archived', 'Archived')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('classification', models.CharField(choices=[('internal', 'Internal'), ('restricted', 'Restricted'), ('confidential', 'Confidential')], default='internal', max_length=20)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_cases', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('relevance', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_links', to='sources.article')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='cases.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='cases.case')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_links', to='sources.entity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cases.case')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_links', to='sources.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('lead', 'Lead'), ('analyst', 'Analyst'), ('viewer', 'Viewer')], default='analyst', max_length=20)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_memberships_assigned', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cases.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['case__title', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='CaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_type', models.CharField(choices=[('analyst_note', 'Analyst Note'), ('finding', 'Finding'), ('update', 'Update')], default='analyst_note', max_length=24)),
                ('body', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_notes_authored', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cases.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_type', models.CharField(choices=[('topic', 'Topic'), ('source', 'Source'), ('alert', 'Alert'), ('external', 'External')], default='external', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('target_app_label', models.CharField(blank=True, max_length=50)),
                ('target_model', models.CharField(blank=True, max_length=50)),
                ('target_object_id', models.CharField(blank=True, max_length=64)),
                ('external_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_references_added', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='cases.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('search_type', models.CharField(choices=[('article', 'Article'), ('event', 'Event'), ('entity', 'Entity'), ('alert', 'Alert')], default='article', max_length=20)),
                ('query_params', models.JSONField(default=dict, help_text='Serialized query parameters.')),
                ('is_global', models.BooleanField(default=False, help_text='Visible to all users.')),
                ('is_pinned', models.BooleanField(default=False)),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('execution_count', models.PositiveIntegerField(default=0)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to='cases.case')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='cases_case_status_5f99d2_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['priority'], name='cases_case_priorit_474e7d_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['classification'], name='cases_case_classif_02aea8_idx'),
        ),
        migrations.AddConstraint(
            model_name='casearticle',
            constraint=models.UniqueConstraint(fields=('case', 'article'), name='uniq_case_article'),
        ),
        migrations.AddConstraint(
            model_name='caseentity',
            constraint=models.UniqueConstraint(fields=('case', 'entity'), name='uniq_case_entity'),
        ),
        migrations.AddConstraint(
            model_name='caseevent',
            constraint=models.UniqueConstraint(fields=('case', 'event'), name='uniq_case_event'),
        ),
        migrations.AddConstraint(
            model_name='casemember',
            constraint=models.UniqueConstraint(fields=('case', 'user'), name='uniq_case_member'),
        ),
        migrations.AddIndex(
            model_name='casereference',
            index=models.Index(fields=['reference_type'], name='cases_caser_referen_f7ae80_idx'),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['search_type'], name='cases_saved_search__997d23_idx'),
        ),
        migrations.AddIndex(
            model_name='savedsearch',
            index=models.Index(fields=['is_global'], name='cases_saved_is_glob_d114a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='savedsearch',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='uniq_saved_search_per_user'),
        ),
    ]
