# Generated by Django 5.1.4 on 2026-04-10 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('task_id', models.CharField(blank=True, max_length=64)),
                ('args', models.JSONField(default=list)),
                ('kwargs', models.JSONField(default=dict)),
                ('exception_type', models.CharField(blank=True, max_length=255)),
                ('exception_message', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('retried', 'Retried'), ('discarded', 'Discarded')], default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=150)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='ops_deadlet_status_b53cd6_idx'), models.Index(fields=['task_name'], name='ops_deadlet_task_na_c813da_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('system', 'System')], default='user', max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('target_app_label', models.CharField(blank=True, max_length=50)),
                ('target_model', models.CharField(blank=True, max_length=50)),
                ('target_object_id', models.CharField(blank=True, max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='ops_auditlo_action_6a326c_idx'), models.Index(fields=['severity'], name='ops_auditlo_severit_491dfe_idx'), models.Index(fields=['target_app_label', 'target_model'], name='ops_auditlo_target__60e1f9_idx')],
            },
        ),
    ]
